version: 0.2

env:
  variables:
    AWS_REGION: ap-south-1
    IMAGE_TAG: latest
    REPOSITORY_URI: 222165755769.dkr.ecr.ap-south-1.amazonaws.com/your-repo-name

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - IMAGE_NAME=$REPOSITORY_URI:$IMAGE_TAG

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $IMAGE_NAME -f ./Dockerfile .

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push $IMAGE_NAME
      - echo Docker image successfully pushed!

artifacts:
  files:
    - '**/*'
